### ISSUE TITLE
Switch to alpine?

### ISSUE THREAD

**Issue by Magi1053** [ehough/docker-nfs-server#15]
You mentioned that...
> Alpine can only be used if/when this bug is fixed: https://bugs.alpinelinux.org/issues/8470

Well it looks like that issue has now been resolved.

**Comment by ehough** [comment]
Thanks for the note and apologies for the late response.

I saw that the bug was fixed and committed, but unfortunately the fix hasn't yet made it to a published version of nfs-utils in the stable repo. I'm checking regularly for that to change, and once it does Alpine will be the default base image for this project.

The fix is, however, in the edge repo and I've got some [preliminary work done](https://github.com/ehough/docker-nfs-server/commit/e95afec52308f7de3d5b7aa24f6c6b027a59d26f) on the [`alpine` branch](https://github.com/ehough/docker-nfs-server/tree/alpine). As you can see the changes are trivial and I don't anticipate any delay once `nfs-utils` is updated by the maintainers.

**Comment by ehough** [comment]
Update. Based upon [what I see](https://pkgs.alpinelinux.org/contents?file=&path=&name=nfs-utils&branch=v3.9&repo=main&arch=x86_64) in the Alpine 3.9 repo for `nfs-utils`, we *should* be ready to make Alpine the base image. I'm going to do some testing today and will post updates here as I have them.

**Comment by ehough** [comment]
Version 2.0.0, which uses Alpine Linux, is [up on Docker Hub](https://hub.docker.com/r/erichough/nfs-server/tags)! So just run `docker pull erichough/nfs-server` and you'll have it.
